### ISSUE TITLE
pybilt on google colab

### ISSUE THREAD

**Issue by andresilvapimentel** [LoLab-MSM/PyBILT#63]
I tried to install the pybilt on google colab but I was not unable. I do not know why.
Could you give any tips, please?
Does it run with python2 or python3?

**Comment by blakeaw** [comment]
Hi @andresilvapimentel 

The latest pybilt version (0.3.0) is only tested with python3, so that's what I'd recommend. 

I'm not sure if there is a better way or not, but the following worked for me to install for use in a single Colab notebook:
1. Install pybilt - Run this command line call at the beginning of the notebook: `!pip install -e git+https://github.com/LoLab-VU/PyBILT@v0.3.0#egg=pybilt`
2. Install MDAnalysis  - run command line call: `!pip install MDAnalysis`
3. Restart the notebook runtime: From the menu: Runtime->Restart runtime

The first command should install pybilt locally in your Colab notebook environment. The second command will install MDAnalysis, which is the only pybilt dependency not included in the default Colab packages. Then, the third step of restarting the Runtime should update the package list for that notebook so that you can import pybilt. Once that is done, you could comment out the pip calls so that it doesn't try to install pybilt/MDAnalysis again if you restart/rerun the notebook later. It looks like if you want to use pybilt again in a different notebook, then you have to repeat the above procedure to install it into that new notebooks environment.   

Let me know if the above works for you or if you run into other issues. 

Best,
Blake
